# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: add-artifactory-user.yml
- include_tasks: add-artifactory-repo.yml
- include_tasks: install-artifactory.yml
- include_role:
    name: configure-artifactory-nodes
- include_tasks: enable-artifactory-service.yml
- include_tasks: start-artifactory-service.yml
- include_tasks: deploy-local-file.yml
  with_items: "{{artifactory_upload_file_list}}"
  loop_control:
    loop_var: upload_filename
